workflows:
  build_flutter_android:
    name: Build Flutter Android APK (Debug)
    max_build_duration: 60
    environment:
      flutter: stable
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - name: Download project zip
        script: |
          set -e
          echo "Downloading project ZIP..."
          wget -O project.zip "https://drive.google.com/uc?export=download&id=1Ym-2BMJhggei0I4iVkumfy8h3PK1liBP"
          unzip -o project.zip -d project
          echo "Moving source into build directory..."
          rsync -a project/ $CM_BUILD_DIR/

      - name: Get Flutter packages
        script: |
          cd $CM_BUILD_DIR
          flutter pub get

      - name: Build debug APK
        script: |
          cd $CM_BUILD_DIR
          flutter build apk --debug

      - name: Copy APK to export directory
        script: |
          mkdir -p $CM_EXPORT_DIR
          cp build/app/outputs/flutter-apk/app-debug.apk $CM_EXPORT_DIR/

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      - $CM_EXPORT_DIR/**
